services:
  image-processor:
    build: .
    volumes:
      - ${INPUT_FOLDER:-./input}:/app/input:ro
      - ${OUTPUT_FOLDER:-./output}:/app/output
    environment:
      - DEFAULT_THREADS=${DEFAULT_THREADS:-4}
      - MAX_THREADS=${MAX_THREADS:-16}