services:
  image-processor:
    build: .
    container_name: libvips-processor
    restart: "no"
    
    volumes:
      - ${INPUT_FOLDER:-./input}:/app/input:ro
      - ${OUTPUT_FOLDER:-./output}:/app/output
      - ${LOG_FOLDER:-./logs}:/tmp/logs
    
    environment:
      - THREADS=${THREADS:-4}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - TZ=${TZ:-UTC}
      - USE_LOCAL_CACHE=${USE_LOCAL_CACHE:-true}
      - CPU_LIMIT=${CPU_LIMIT:-6.0}
    
    # 资源限制（CPU 限制适度高于线程数以避免资源竞争）
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-2G}
          cpus: '${CPU_LIMIT}'
        reservations:
          memory: 512M
          cpus: '1.0'
    
    # 安全配置
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:noexec,nosuid,size=4g